@@ -4,3 +4,175 @@ info:
   version: 1.0.0
 apis:
   - ./src/routes/routes
+servers:
+  -url: http://api.example.com/v1
+paths:
+  /cards:
+    get:
+      summary: Returns array of cards
+      security:
+        - BearerAuth: []
+    responses:
+      '200':
+      description: Successful operation
+      content:
+        application/json:
+          schema:
+            type: array
+              items: 
+                type: object
+                properties:
+                  front:
+                    type: string
+                    description: Text in first side of the card
+                  back:
+                    type: string
+                    description: Text in second side of the card
+                  tags:
+                    type: array
+                    items:
+                      type: string
+                    description: Tags related to the card
+                  author:
+                    type: string
+                    description: Author of the card
+        "404":
+        description: Cards not found
+        content:
+          application/json:
+            example:
+              error: "Cards not found"
+              details: "Cards not found in the database. Check database connection and make sure it is not empty"
+        "500":
+        description: Problem with the server
...
...
...
  /cards/{id}:
...
...
...
    delete:
+      summary: Delete the card
+      parameters:
+        - name: id
+          in: path
+          required: true
+          schema:
+            type: string
+          description: Card's ID
+      security:
+        - BearerAuth: []
+      responses:
+        '204':
+          description: Deleting succesfull
+        '403':
+          description: Card not found or It is not allowed to delete the card after 5 minutes of its creation or card not found.
+        '400':
+          description: Invalid card ID